version: '2.3'
services:
 sirf:
  image: synerbi/sirf:jupyterhub
  restart: unless-stopped
  environment:
   GADGETRON_RELAY_HOST: 0.0.0.0
  build:
   target: jupyterhub
   cache_from:
    - synerbi/sirf:core
    - synerbi/sirf:latest
    - synerbi/sirf:jupyterhub
  # ports:
   # - "9002:9002"  # gadgetron
   #  - "9999:8888"  # jupyter
   # for scaling, use this instead for random port assignment
   # (https://github.com/docker/compose/issues/2260):
   #- "9000-9099:9002"
   #- "8800-8899:8888"
