version: '2.3'
services:
 sirf:
  image: synerbi/sirf:service-multi
  build:
   target: multi
   cache_from:
    - synerbi/sirf:core
    - synerbi/sirf:latest
    - synerbi/sirf:service
    - synerbi/sirf:service-multi
  ports:
   - "8890-8899:8890-8899"
